[versions]
nexus-publish = "2.0.0"

# libraries
gson = "2.13.2"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }